### ISSUE TITLE
Setup for the NumPy speed comparison?

### ISSUE THREAD

**Issue by shoyer** [deeplearning4j/nd4j-benchmark#3]
On your website, you report that ND4J runs twice as fast as NumPy for matrix multiplication.

This strikes me as *highly* questionable. In both cases, NumPy and ND4J are doing matrix multiplication by calling out to an external BLAS. So you're really measuring the speed of the external BLAS. Moreover, ND4J needs to copy data as it is goes in and out of the JVM, which is often not the case for NumPy.

My guess is that you're linking to a different BLAS with NumPy, which results in the observed speed difference.

**Comment by agibsonccc** [comment]
We'll be adding to this here soon with different versions of blas. Please come on gitter if you'd like to ask more questions about this. Thanks!

**Comment by cinqs** [comment]
Hi, Just run these codes on the same computer, turns out *Numpy* is about 5 times faster than *ND4J*, correct me if I am wrong.

```java

import java.sql.Timestamp;
import java.util.Random;

import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.factory.Nd4j;

public class Main {
	
	public static void main(String [] args) {
		Random rand = new Random();
		int length = 1_000_000;
		double[] d1 = new double[length];
		double[] d2 = new double[length];
		
		for(int i = 0; i < length; i++) {
			d1[i] = rand.nextDouble();
			d2[i] = rand.nextDouble();
		}
		
		INDArray nd1 = Nd4j.create(d1, new int[] {1, length});
		INDArray nd2 = Nd4j.create(d2, new int[] {length, 1});
		
		long t1 = timeNow();
		
		INDArray nd3 = nd1.mmul(nd2);
		
		
		long t2 = timeNow();
		print(nd3);
		
		double d = 0;
		for(int i = 0; i < length; i++) {
			d += d1[i] * d2[i];
		}
		
		
		long t3 = timeNow();
		print(d);
		print("ND4J cost time: " + Long.toString(t2 - t1));
		print("For Loop cost time: " + Long.toString(t3 - t2));
	}
	
	private static void print(Object o) {
		System.out.println(o);
	}
	
	private static long timeNow() {
		return System.currentTimeMillis();
	}
}

```
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>group.id</groupId>
  <artifactId>nd4j-test</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>nd4j-test</name>
  <description>nd4j-test</description>
  <properties>
  	<maven.compiler.source>1.7</maven.compiler.source>
  	<maven.compiler.target>1.7</maven.compiler.target>
        <exec.mainClass>Main</exec.mainClass>
  </properties>
  <dependencies>
  	<dependency>
  		<groupId>org.nd4j</groupId>
  		<artifactId>nd4j-native-platform</artifactId>
  		<version>0.9.1</version>
  	</dependency>
  	<dependency>
	    <groupId>org.slf4j</groupId>
	    <artifactId>slf4j-log4j12</artifactId>
	    <version>1.7.25</version>
	    <scope>test</scope>
	</dependency>
  	
  </dependencies>
</project>
```

Output is:

```console
250,561.16
250561.20823672338
ND4J cost time: 5
For Loop cost time: 274
```

Meantime, the *ND4J* codes below:

```python
import numpy as np
import time

length = 1000000

a = np.random.rand(length)
b = np.random.rand(length)

t1 = time.time()
c = np.dot(a, b)
t2 = time.time()

print(str(1000 * (t2 - t1)))
```

The output is:

```console
0.638008117676
```

**Comment by cinqs** [comment]
Sorry for not carefully handle the test, after test them with 100 iterations:

```java
double all = 0d;
                for(int i = 0; i < 100; i++) {
                        long t1 = timeNow();
                        nd1.mmul(nd2);
                        long t2 = timeNow();
                        all += (t2 - t1);
                }

                print(all / 100);
```

Output:
```console
98.3
```

```python
all = 0.0
count = 0
for i in range(100):
  t1 = time.time()

  c = np.dot(a, b)

  t2 = time.time()
  count += 1
  all += (t2 - t1) * 1000

print(str(all / count))
```

Output:
```console
221.279616356
```

Yes, your are right, *ND4J* is almost twice faster than *Numpy*

**Comment by MartinThoma** [comment]
@cinqs Do you have a reason why ND4j should be faster? I think the argument of @shoyer sounds reasonable:

>  In both cases, NumPy and ND4J are doing matrix multiplication by calling out to an external BLAS. So you're really measuring the speed of the external BLAS.

**Comment by brokndremes** [comment]
> @cinqs Do you have a reason why ND4j should be faster? I think the argument of @shoyer sounds reasonable:
> 
> > In both cases, NumPy and ND4J are doing matrix multiplication by calling out to an external BLAS. So you're really measuring the speed of the external BLAS.

The differenc eis probably due to loop unrolling in the java code. Can make a better comparison - strictly between numpy and ND4J that is - by disabling that optimization with XX:LoopUnrollLimit.
